# Generated by Django 3.2 on 2023-07-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingsession',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='creation_date',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='time_of_reading',
            field=models.TimeField(),
        ),
    ]
