# Generated by Django 3.2 on 2023-07-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0002_auto_20230705_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='readed_pages',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
