# Generated by Django 3.2 on 2023-07-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0003_readingsession_readed_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingsession',
            name='creation_date',
        ),
    ]
