# Generated by Django 3.2 on 2023-07-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0004_remove_readingsession_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
