# Generated by Django 3.2 on 2023-07-19 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLectureGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_page_per_day', models.IntegerField()),
                ('goal_reading_speed', models.IntegerField()),
                ('goal_sessions_per_day', models.TimeField()),
                ('goal_hours_per_day', models.TimeField()),
                ('goal_book_per_year', models.TimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
