# Generated by Django 3.2 on 2023-07-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_lecture_goal', '0002_auto_20230719_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlecturegoal',
            name='goal_book_per_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlecturegoal',
            name='goal_sessions_per_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
