# Generated by Django 3.2 on 2023-07-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_lecture_goal', '0003_auto_20230719_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlecturegoal',
            name='goal_book_per_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlecturegoal',
            name='goal_hours_per_day',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlecturegoal',
            name='goal_page_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlecturegoal',
            name='goal_reading_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlecturegoal',
            name='goal_sessions_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
