# Generated by Django 3.2 on 2023-07-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_lecture_goal', '0004_auto_20230719_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlecturegoal',
            old_name='goal_page_per_day',
            new_name='goal_page_per_day_last_week',
        ),
        migrations.RenameField(
            model_name='userlecturegoal',
            old_name='goal_hours_per_day',
            new_name='goal_readed_hours_day_last_week',
        ),
        migrations.RenameField(
            model_name='userlecturegoal',
            old_name='goal_reading_speed',
            new_name='goal_sessions_per_day_sum_last_week',
        ),
        migrations.RenameField(
            model_name='userlecturegoal',
            old_name='goal_sessions_per_day',
            new_name='goal_velocidad_lectura',
        ),
    ]
