# Generated by Django 3.2 on 2023-07-02 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=13)),
                ('publication_date', models.DateField()),
                ('total_pages', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('resume', models.TextField()),
                ('genre', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='book_covers/')),
                ('reading_status_porcentaje', models.IntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
