# Generated by Django 3.2 on 2023-07-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2),
        ),
    ]
